package com.grabbill.core.model;

/**
 * @author michaellow
 */
public enum ActionType {

    TYPE_CREATE,
    TYPE_UPDATE,
    TYPE_DELETE,
    TYPE_DUPLICATE,

    ACTIVITY_CREATE,
    ACTIVITY_UPDATE,
    ACTIVITY_SUBMIT,

    ACTIVITY_SCHEDULE,
    ACTIVITY_PROCESS,
    ACTIVITY_PURGE,
    ACTIVITY_DELETE,
    ACTIVITY_FILE_UPLOAD,
    ACTIVITY_FILE_DOWNLOAD,
    ACTIVITY_FILE_EXPORT,
    ACTIVITY_FILE_DELETE,

    JOB_CREATE,
    JOB_SUBMIT,
    JOB_RETRY,
    JOB_PROCESS_START,
    JOB_PROCESS_END,

    UPDATE_PLAN,

    CREATE,
    UPDATE,
    DELETE,
    BULK_DELETE,

    SUBSCRIBE,
    SWITCH,

    ACTIVATE,
    DEACTIVATE,
    MARK_GUIDED_STEPS_VIEWED,
    RESET_USER_PASSWORD,

    REGISTER,
    CHANGE_PASSWORD,

    SEND_VERIFY_EMAIL,

    FORGET_PASSWORD,
    VERIFY_EMAIL,
    RESET_PASSWORD,
    GENERATE_EMAIL_OTP,
    GENERATE_EMAIL_2FA_ACTIVATION_OTP,

    UPLOAD,

    CONTACT_UPDATE_DETAILS,
    CONTACT_UPDATE_GROUPS,

    LOGIN,
    LOGOUT,

    CREDIT_TOPUP,

    WABA_UPDATE,
    WABA_WEBHOOK_REGISTERED,
    WABA_WEBHOOK_UNREGISTERED,
    WABA_AUTO_REPLY_MESSAGE_UPDATE,

    SFTP_UPDATE

}
