import { NgModule } from '@angular/core';
import { NZ_ICONS, NzIconModule } from 'ng-zorro-antd/icon';

import {
  BankOutline,
  CheckCircleOutline,
  CheckCircleTwoTone,
  CloseOutline,
  ContactsOutline,
  ContainerOutline,
  CopyOutline,
  CreditCardOutline,
  DashboardOutline,
  DeleteOutline,
  DollarOutline,
  DownloadOutline,
  EditOutline,
  ExceptionOutline,
  FieldTimeOutline,
  FileOutline,
  FilePdfOutline,
  FileTextOutline,
  FilterOutline,
  FolderOutline,
  FormOutline,
  GlobalOutline,
  GoogleOutline,
  HistoryOutline,
  HomeOutline,
  InboxOutline,
  InfoCircleOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MessageOutline,
  MobileOutline,
  NumberOutline,
  PhoneOutline,
  PictureOutline,
  PlusOutline,
  ProfileOutline,
  RedoOutline,
  SearchOutline,
  SettingOutline,
  SolutionOutline,
  SwapOutline,
  TableOutline,
  TeamOutline,
  UserOutline,
} from '@ant-design/icons-angular/icons';

const icons = [
  BankOutline,
  CheckCircleOutline,
  CheckCircleTwoTone,
  CloseOutline,
  ContactsOutline,
  ContainerOutline,
  CopyOutline,
  CreditCardOutline,
  DashboardOutline,
  DeleteOutline,
  DollarOutline,
  DownloadOutline,
  EditOutline,
  ExceptionOutline,
  FieldTimeOutline,
  FilePdfOutline,
  FileOutline,
  FileTextOutline,
  FilterOutline,
  FolderOutline,
  GlobalOutline,
  GoogleOutline,
  HistoryOutline,
  InboxOutline,
  InfoCircleOutline,
  LockOutline,
  LogoutOutline,
  HomeOutline,
  RedoOutline,
  MailOutline,
  MessageOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MobileOutline,
  NumberOutline,
  PictureOutline,
  PhoneOutline,
  PlusOutline,
  ProfileOutline,
  SearchOutline,
  SettingOutline,
  SolutionOutline,
  SwapOutline,
  TableOutline,
  TeamOutline,
  UserOutline,
  FormOutline,
];

@NgModule({
  imports: [NzIconModule],
  exports: [NzIconModule],
  providers: [{ provide: NZ_ICONS, useValue: icons }],
})
export class IconsProviderModule {}
