export const environment = {
  production: true,
  config: {
    appUrl: 'https://app.uat.grabbill.com',
    baseApiUrl: 'https://api.uat.grabbill.com',
    websiteUrl: 'https://www.uat.grabbill.com',
    shortDateFormat: 'dd/MM/yyyy',
    dateFormat: 'dd/MM/yyyy, h:mm:ss a',
    maxIndexRow: 20000,
    maxPdfFileSizeBytes: 20000000,
    maxZipFileSizeBytes: 500000000,
    maxFileSizeBytes: 10000000,
    experimentalFeature: true,
    contextSensitiveHelp: false,
    supportEmail: 'support@mybillone.com',
    smtpFromEmail: 'uat@mybillone.com',
    maxImageSizeBytes: 20000000,
    maxImageTotal: 100,
    canTopUpSms: false,
    isPaidPlanEnabled: true,
    deploymentMode: 'saas',
    firebase: {
      apiKey: 'AIzaSyDyJuNKvDafHUppgYRyFiVZjUJX4Mui1HE',
      authDomain: 'grabbill-uat.firebaseapp.com',
      projectId: 'grabbill-uat',
      storageBucket: 'grabbill-uat.appspot.com',
      messagingSenderId: '502434435162',
      appId: '1:502434435162:web:ef67d5ec4698201526c863',
      measurementId: 'G-EHY9BXHZR0',
    },
  },
};
