export const environment = {
  production: true,
  config: {
    appUrl: 'https://app.mybillone.com',
    baseApiUrl: 'https://api.mybillone.com',
    websiteUrl: 'https://www.mybillone.com',
    shortDateFormat: 'dd/MM/yyyy',
    dateFormat: 'dd/MM/yyyy, h:mm:ss a',
    maxIndexRow: 20000,
    maxPdfFileSizeBytes: 20000000,
    maxZipFileSizeBytes: 500000000,
    maxFileSizeBytes: 10000000,
    experimentalFeature: false,
    contextSensitiveHelp: false,
    supportEmail: 'support@mybillone.com',
    smtpFromEmail: 'no-reply@mybillone.com',
    maxImageSizeBytes: 20000000,
    maxImageTotal: 100,
    canTopUpSms: false,
    isPaidPlanEnabled: true,
    deploymentMode: 'saas',
    firebase: {
      apiKey: 'AIzaSyCF71pgfqnfw6zU5N-itrAcy9-u2TuHvIE',
      authDomain: 'grabbill.firebaseapp.com',
      projectId: 'grabbill',
      storageBucket: 'grabbill.appspot.com',
      messagingSenderId: '203015914730',
      appId: '1:203015914730:web:c13798b88acbc7e01b8393',
      measurementId: 'G-88FBSMC00D',
    },
  },
};
